site_name: Accelbyte UE4 SDK Documentation Page
theme: material
nav:
    - Getting Started:
        - 'Overview': 'overview.md'
        - 'Configuration': 'configuration.md'
    - User Guide:
        - 'Using the SDK': 'usingTheSdk.md'
        - 'Integrate with Steam': 'steamIntegration.md'
    - API Docs:
        - 'Blueprints': 'blueprints.md'
        - 'Functions': 'functions.md'
        - 'Models': 'models.md'
        - 'Callback': 'callback.md'
    - Third-Party's Utilities Usage:
        - 'Steamworks SDK': 'Steamworks.md'
repo_name: Bitbucket