apiVersion: "v1"
kind: GameServer
metadata:
  name: my-local-server-SDK
  annotations:
    match-details: "{
      \"Session_id\":\"0123456789\",
      \"Namespace\":\"sdk namespace should be here\",
      \"Game_mode\":\"your requested game mode should be here\",
      \"Matching_allies\":[
        {
          \"Matching_parties\":[
            {
              \"Party_id\":\"party001\",
              \"Party_members\":
                [
                  {
                    \"User_id\":\"XX001\"
                  },
                  {
                    \"User_id\":\"XX002\"
                  },
                  {
                    \"User_id\":\"XX003\"
                  }
                ]
            },
            {
              \"Party_id\":\"party002\",
              \"Party_members\":
                [
                  {
                    \"User_id\":\"XY001\"
                  },
                  {
                    \"User_id\":\"XY002\"
                  },
                  {
                    \"User_id\":\"XY003\"
                  }
                ]
            }
          ]
        }
      ]
    }
    "
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
          
